
spring.application.name=TicketBookingService
server.port=8080

#DataSource Config:
spring.datasource.url=jdbc:mysql://localhost:3306/finishers
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

# Swagger UI at http://localhost:8080/swagger-ui/index.html
springdoc.api-docs.path=/api-docs

