# ======================================================
# TicketBookingGateway ? application.properties (:8081)
# ======================================================
 spring.application.name=TicketBookingGateway
 server.port=8081
 ticketservice.base-url=http://localhost:8080